export const DEFAULT_RULES: { pattern: string; categoryName: string }[] = [
  { pattern: "UBER", categoryName: "App de transporte" },
  { pattern: "99APP", categoryName: "App de transporte" },
  { pattern: "99POP", categoryName: "App de transporte" },
  { pattern: "IFOOD", categoryName: "Delivery" },
  { pattern: "RAPPI", categoryName: "Delivery" },
  { pattern: "NETFLIX", categoryName: "Assinaturas e streaming" },
  { pattern: "SPOTIFY", categoryName: "Assinaturas e streaming" },
  { pattern: "AMAZON PRIME", categoryName: "Assinaturas e streaming" },
  { pattern: "DISNEY", categoryName: "Assinaturas e streaming" },
  { pattern: "HBO", categoryName: "Assinaturas e streaming" },
  { pattern: "POSTO", categoryName: "Combustível" },
  { pattern: "SHELL", categoryName: "Combustível" },
  { pattern: "IPIRANGA", categoryName: "Combustível" },
  { pattern: "FARMACIA", categoryName: "Farmácia" },
  { pattern: "DROGARIA", categoryName: "Farmácia" },
  { pattern: "DROGASIL", categoryName: "Farmácia" },
  { pattern: "SUPERMERCADO", categoryName: "Supermercado" },
  { pattern: "MERCADO", categoryName: "Supermercado" },
  { pattern: "CARREFOUR", categoryName: "Supermercado" },
  { pattern: "PAO DE ACUCAR", categoryName: "Supermercado" },
  { pattern: "RESTAURANTE", categoryName: "Restaurantes" },
  { pattern: "LANCHONETE", categoryName: "Restaurantes" },
  { pattern: "PADARIA", categoryName: "Restaurantes" },
  { pattern: "SALARIO", categoryName: "Salário" },
  { pattern: "PAGAMENTO SALARIO", categoryName: "Salário" },
  { pattern: "ENERGIA", categoryName: "Energia" },
  { pattern: "ENEL", categoryName: "Energia" },
  { pattern: "CPFL", categoryName: "Energia" },
  { pattern: "SABESP", categoryName: "Água" },
  { pattern: "COPASA", categoryName: "Água" },
  { pattern: "VIVO", categoryName: "Internet" },
  { pattern: "CLARO", categoryName: "Internet" },
  { pattern: "TIM", categoryName: "Internet" },
  { pattern: "OI FIBRA", categoryName: "Internet" },
  { pattern: "ALUGUEL", categoryName: "Aluguel" },
  { pattern: "CONDOMINIO", categoryName: "Condomínio" },
  { pattern: "UNIMED", categoryName: "Plano de saúde" },
  { pattern: "AMIL", categoryName: "Plano de saúde" },
  { pattern: "HAPVIDA", categoryName: "Plano de saúde" },
];
